#!/usr/bin/env python3
"""
Hello World Execution Script.
Validates inputs, generates a personalized markdown greeting report,
and saves it to the temporary directory.
"""

import os
import sys
import argparse
from datetime import datetime

def parse_arguments():
    parser = argparse.ArgumentParser(description="Generate a personalized greeting report.")
    parser.add_argument("--name", required=True, help="The name of the user to greet.")
    parser.add_argument("--title", default=None, help="The optional job title or role of the user.")
    return parser.parse_args()

def main():
    args = parse_arguments()
    name = args.name.strip()
    title = args.title.strip() if args.title else None

    if not name:
        print("Error: The --name parameter cannot be empty.", file=sys.stderr)
        sys.exit(1)

    # Establish output paths and directories
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    tmp_dir = os.path.join(project_root, "tmp")

    if not os.path.exists(tmp_dir):
        os.makedirs(tmp_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_filename = f"greeting_{timestamp}.md"
    output_path = os.path.join(tmp_dir, output_filename)

    # Compile report content
    title_suffix = f" ({title})" if title else ""
    report_content = f"""# Personalized Greeting Report

Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Welcome, {name}{title_suffix}!

This document was successfully generated by the Layer 3 execution tool (`execution/hello_world.py`) following the Standard Operating Procedure laid out in Layer 1 (`directives/hello_world.md`).

### System Environment Status
- **Project Directory:** `{project_root}`
- **Execution Script:** `execution/hello_world.py`
- **Output File:** `{output_path}`
- **Status:** **Ready for Agent Orchestration**
"""

    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report_content)
        
        print(f"Success: Report generated successfully at {output_path}")
        # Write output path to stdout so orchestrator can read it
        print(f"OUTPUT_PATH={output_path}")
    except Exception as e:
        print(f"Error: Failed to write report file: {e}", file=sys.stderr)
        sys.exit(2)

if __name__ == "__main__":
    main()
